import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: { formats: ["image/avif", "image/webp"] },
  async redirects() {
    return [
      { source: "/atendentes-de-bar-para-shows-em-sp.php", destination: "/atendentes-de-bar-para-shows-em-sp", permanent: true },
      { source: "/atendentes-de-bar-para-shows-no-abc.php", destination: "/atendentes-de-bar-para-shows-no-abc", permanent: true },
      { source: "/atendentes-de-bar-para-shows.php", destination: "/atendentes-de-bar-para-shows", permanent: true },
      { source: "/barman-para-aniversario-em-alphaville.php", destination: "/barman-para-aniversario-em-alphaville", permanent: true },
      { source: "/barman-para-aniversario-em-atibaia.php", destination: "/barman-para-aniversario-em-atibaia", permanent: true },
      { source: "/barman-para-aniversario-em-santo-andre.php", destination: "/barman-para-aniversario-em-santo-andre", permanent: true },
      { source: "/barman-para-aniversario-em-sao-caetano.php", destination: "/barman-para-aniversario-em-sao-caetano", permanent: true },
      { source: "/barman-para-aniversario-em-sp.php", destination: "/barman-para-aniversario-em-sp", permanent: true },
      { source: "/barman-para-aniversario-na-aldeia-da-serra.php", destination: "/barman-para-aniversario-na-aldeia-da-serra", permanent: true },
      { source: "/barman-para-aniversario-na-granja-viana.php", destination: "/barman-para-aniversario-na-granja-viana", permanent: true },
      { source: "/barman-para-aniversario.php", destination: "/barman-para-aniversario", permanent: true },
      { source: "/barman-para-casamento-em-alphaville.php", destination: "/barman-para-casamento-em-alphaville", permanent: true },
      { source: "/barman-para-casamentos-em-sp.php", destination: "/barman-para-casamentos-em-sp", permanent: true },
      { source: "/barman-para-casamentos.php", destination: "/barman-para-casamentos", permanent: true },
      { source: "/barman-para-eventos-barato.php", destination: "/barman-para-eventos-barato", permanent: true },
      { source: "/barman-para-eventos-em-alphaville.php", destination: "/barman-para-eventos-em-alphaville", permanent: true },
      { source: "/barman-para-eventos-em-guarulhos.php", destination: "/barman-para-eventos-em-guarulhos", permanent: true },
      { source: "/barman-para-eventos-em-ilhabela.php", destination: "/barman-para-eventos-em-ilhabela", permanent: true },
      { source: "/barman-para-eventos-em-santo-andre.php", destination: "/barman-para-eventos-em-santo-andre", permanent: true },
      { source: "/barman-para-eventos-em-sao-bernardo.php", destination: "/barman-para-eventos-em-sao-bernardo", permanent: true },
      { source: "/barman-para-eventos-em-sao-caetano.php", destination: "/barman-para-eventos-em-sao-caetano", permanent: true },
      { source: "/barman-para-eventos-em-sp.php", destination: "/barman-para-eventos-em-sp", permanent: true },
      { source: "/barman-para-eventos-no-abc.php", destination: "/barman-para-eventos-no-abc", permanent: true },
      { source: "/barman-para-eventos-no-guaruja.php", destination: "/barman-para-eventos-no-guaruja", permanent: true },
      { source: "/barman-para-eventos-no-litoral-de-sp.php", destination: "/barman-para-eventos-no-litoral-de-sp", permanent: true },
      { source: "/barman-para-eventos-no-litoral-norte.php", destination: "/barman-para-eventos-no-litoral-norte", permanent: true },
      { source: "/barman-para-eventos-preco.php", destination: "/barman-para-eventos-preco", permanent: true },
      { source: "/barman-para-eventos-valor.php", destination: "/barman-para-eventos-valor", permanent: true },
      { source: "/barman-para-eventos.php", destination: "/barman-para-eventos", permanent: true },
      { source: "/barman-para-festas-em-alphaville.php", destination: "/barman-para-festas-em-alphaville", permanent: true },
      { source: "/barman-para-festas-em-guarulhos.php", destination: "/barman-para-festas-em-guarulhos", permanent: true },
      { source: "/barman-para-festas-em-ilhabela.php", destination: "/barman-para-festas-em-ilhabela", permanent: true },
      { source: "/barman-para-festas-em-santo-andre.php", destination: "/barman-para-festas-em-santo-andre", permanent: true },
      { source: "/barman-para-festas-em-sao-bernardo.php", destination: "/barman-para-festas-em-sao-bernardo", permanent: true },
      { source: "/barman-para-festas-em-sao-caetano.php", destination: "/barman-para-festas-em-sao-caetano", permanent: true },
      { source: "/barman-para-festas-em-sp.php", destination: "/barman-para-festas-em-sp", permanent: true },
      { source: "/barman-para-festas-no-abc.php", destination: "/barman-para-festas-no-abc", permanent: true },
      { source: "/barman-para-festas-no-guaruja.php", destination: "/barman-para-festas-no-guaruja", permanent: true },
      { source: "/barman-para-festas-no-litoral-de-sp.php", destination: "/barman-para-festas-no-litoral-de-sp", permanent: true },
      { source: "/barman-para-festas-no-litoral-norte.php", destination: "/barman-para-festas-no-litoral-norte", permanent: true },
      { source: "/barman-para-festas.php", destination: "/barman-para-festas", permanent: true },
      { source: "/barman-para-formatura-em-sp.php", destination: "/barman-para-formatura-em-sp", permanent: true },
      { source: "/barman-para-formatura-no-abc.php", destination: "/barman-para-formatura-no-abc", permanent: true },
      { source: "/barman-para-formatura.php", destination: "/barman-para-formatura", permanent: true },
      { source: "/garcom-para-eventos-barato.php", destination: "/garcom-para-eventos-barato", permanent: true },
      { source: "/garcom-para-eventos-em-alphaville.php", destination: "/garcom-para-eventos-em-alphaville", permanent: true },
      { source: "/garcom-para-eventos-em-guarulhos.php", destination: "/garcom-para-eventos-em-guarulhos", permanent: true },
      { source: "/garcom-para-eventos-em-ilhabela.php", destination: "/garcom-para-eventos-em-ilhabela", permanent: true },
      { source: "/garcom-para-eventos-em-santo-andre.php", destination: "/garcom-para-eventos-em-santo-andre", permanent: true },
      { source: "/garcom-para-eventos-em-sao-bernardo.php", destination: "/garcom-para-eventos-em-sao-bernardo", permanent: true },
      { source: "/garcom-para-eventos-em-sao-caetano.php", destination: "/garcom-para-eventos-em-sao-caetano", permanent: true },
      { source: "/garcom-para-eventos-em-sp.php", destination: "/garcom-para-eventos-em-sp", permanent: true },
      { source: "/garcom-para-eventos-no-guaruja.php", destination: "/garcom-para-eventos-no-guaruja", permanent: true },
      { source: "/garcom-para-eventos-no-litoral-norte.php", destination: "/garcom-para-eventos-no-litoral-norte", permanent: true },
      { source: "/garcom-para-eventos-no-litoral-sul.php", destination: "/garcom-para-eventos-no-litoral-sul", permanent: true },
      { source: "/garcom-para-eventos-preco.php", destination: "/garcom-para-eventos-preco", permanent: true },
      { source: "/garcom-para-eventos-valor.php", destination: "/garcom-para-eventos-valor", permanent: true },
      { source: "/garcom-para-eventos.php", destination: "/garcom-para-eventos", permanent: true },
      { source: "/garcom-para-festas-barato.php", destination: "/garcom-para-festas-barato", permanent: true },
      { source: "/garcom-para-festas-em-alphaville.php", destination: "/garcom-para-festas-em-alphaville", permanent: true },
      { source: "/garcom-para-festas-em-guarulhos.php", destination: "/garcom-para-festas-em-guarulhos", permanent: true },
      { source: "/garcom-para-festas-em-ilhabela.php", destination: "/garcom-para-festas-em-ilhabela", permanent: true },
      { source: "/garcom-para-festas-em-santo-andre.php", destination: "/garcom-para-festas-em-santo-andre", permanent: true },
      { source: "/garcom-para-festas-em-sao-bernardo.php", destination: "/garcom-para-festas-em-sao-bernardo", permanent: true },
      { source: "/garcom-para-festas-em-sao-caetano.php", destination: "/garcom-para-festas-em-sao-caetano", permanent: true },
      { source: "/garcom-para-festas-em-sp.php", destination: "/garcom-para-festas-em-sp", permanent: true },
      { source: "/garcom-para-festas-no-guaruja.php", destination: "/garcom-para-festas-no-guaruja", permanent: true },
      { source: "/garcom-para-festas-no-litoral-norte.php", destination: "/garcom-para-festas-no-litoral-norte", permanent: true },
      { source: "/garcom-para-festas-preco.php", destination: "/garcom-para-festas-preco", permanent: true },
      { source: "/garcom-para-festas-valor.php", destination: "/garcom-para-festas-valor", permanent: true },
      { source: "/garcom-para-festas.php", destination: "/garcom-para-festas", permanent: true },
      { source: "/servico-de-bar-para-eventos-barato.php", destination: "/servico-de-bar-para-eventos-barato", permanent: true },
      { source: "/servico-de-bar-para-eventos-em-guarulhos.php", destination: "/servico-de-bar-para-eventos-em-guarulhos", permanent: true },
      { source: "/servico-de-bar-para-eventos-em-mairipora.php", destination: "/servico-de-bar-para-eventos-em-mairipora", permanent: true },
      { source: "/servico-de-bar-para-eventos-em-santo-andre.php", destination: "/servico-de-bar-para-eventos-em-santo-andre", permanent: true },
      { source: "/servico-de-bar-para-eventos-em-sao-bernardo.php", destination: "/servico-de-bar-para-eventos-em-sao-bernardo", permanent: true },
      { source: "/servico-de-bar-para-eventos-em-sao-caetano.php", destination: "/servico-de-bar-para-eventos-em-sao-caetano", permanent: true },
      { source: "/servico-de-bar-para-eventos-em-sp.php", destination: "/servico-de-bar-para-eventos-em-sp", permanent: true },
      { source: "/servico-de-bar-para-eventos-no-abc.php", destination: "/servico-de-bar-para-eventos-no-abc", permanent: true },
      { source: "/servico-de-bar-para-eventos-preco.php", destination: "/servico-de-bar-para-eventos-preco", permanent: true },
      { source: "/servico-de-bar-para-eventos-valor.php", destination: "/servico-de-bar-para-eventos-valor", permanent: true },
      { source: "/servico-de-bar-para-eventos.php", destination: "/servico-de-bar-para-eventos", permanent: true },
      { source: "/quem-somos.php", destination: "/empresa", permanent: true },
      { source: "/cardapio.php", destination: "/cardapio", permanent: true },
      { source: "/galeria.php", destination: "/galeria", permanent: true },
      { source: "/contato.php", destination: "/contato", permanent: true },
      { source: "/sobre-nos", destination: "/empresa", permanent: true },
      { source: "/quem-somos", destination: "/empresa", permanent: true },
    ];
  },
};

export default nextConfig;
